version: 2.1

jobs: 
  run-unit-tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    description: "Run unit tests"
    steps:
      - checkout
      - run: 
          name: "Install Packages"
          command: npm install 
      - run: 
          name: "Run Unit Tests"
          command: npm run test    


workflows:
  main:
    jobs:
      - run-unit-tests